project_id = "xbqslsxaskrdxgoxtjoh"

[functions.approve-freelancer]
verify_jwt = false

[functions.escrow-create]
verify_jwt = false

[functions.escrow-release]
verify_jwt = false

[functions.escrow-status]
verify_jwt = false

[functions.resend-activation]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.escrow-webhook]
verify_jwt = false

[functions.process-notifications]
verify_jwt = false
import_map = "./functions/process-notifications/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/process-notifications/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/process-notifications/*.html" ]

[functions.resend-webhook]
enabled = true
verify_jwt = true
import_map = "./functions/resend-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/resend-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/resend-webhook/*.html" ]

[functions.cron-reconcile-escrow]
enabled = true
verify_jwt = true
import_map = "./functions/cron-reconcile-escrow/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/cron-reconcile-escrow/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/cron-reconcile-escrow/*.html" ]
