project_id = "xbqslsxaskrdxgoxtjoh"

[functions.approve-freelancer]
verify_jwt = false

[functions.escrow-create]
verify_jwt = false

[functions.escrow-release]
verify_jwt = false

[functions.escrow-status]
verify_jwt = false

[functions.resend-activation]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.escrow-webhook]
verify_jwt = false
